### ISSUE TITLE
Images not loading using cocoapods, swift and Xcode 7 beta 5

### ISSUE THREAD

**Issue by katalisha** [nakiostudio/NKO-Color-Picker-View-iOS#10]
Thanks for making such an excellent library!

Images aren't loading for me, all the UIImage calls are returning nil when including the library with cocoa pods. The sample project loads just fine.

I was able to get it working by manually adding the images to the copy bundle resources build phase. It may be a cocoa pods problem but I thought I would let you know.

Thanks again!

**Comment by nakiostudio** [comment]
Should be fixed on 0.4
