### ISSUE TITLE
Color picker view is not resizing

### ISSUE THREAD

**Issue by belovictor** [nakiostudio/NKO-Color-Picker-View-iOS#11]
NKOColorPickerView is not resizing on screen rotation. Screenshot attached.
![screen shot 2015-10-13 at 10 44 27](https://cloud.githubusercontent.com/assets/1630396/10448817/15feb28e-7198-11e5-84d3-c2380da353ae.png)

**Comment by nakiostudio** [comment]
Hi @belovictor, is this still an issue?

**Comment by belovictor** [comment]
No, my stupidness was the issue :-)

**Comment by nakiostudio** [comment]
No worries hehe mine will arise at some point, anyway keep reporting :-)
